### ISSUE TITLE
About

### ISSUE THREAD

**Issue by juanfrans** [CenterForSpatialResearch/locationsofjustice#1]
Add an "About" link as a popup in the map to explain what we are trying to show here.

**Comment by vomc** [comment]
add a pop up on the map with the about information
add some lorem ipsum for now with a placeholder image etc

**Comment by vomc** [comment]
link should say 'about this map' and pop open a modal window with some lorem ipsum for now

**Comment by vomc** [comment]
closing this for now, might need to swap copy once Laura revises this weekend
